"""Replace implementations here without changing REST, MCP, or UI contracts."""

from collections.abc import Callable
from dataclasses import dataclass
from typing import Protocol

import numpy as np

from .domain import PlanResult, PlanSnapshot

Progress = Callable[[float, str], None]


class EphemerisProvider(Protocol):
    name: str

    def positions(self, spacecraft: list[dict], unix_seconds: np.ndarray) -> np.ndarray:
        """Return Float64 ECEF meters shaped (time, spacecraft, xyz). No extrapolation."""
        ...


@dataclass
class SolvedPlan:
    result: PlanResult
    positions: bytes
    targets: bytes


class Scheduler(Protocol):
    name: str

    def solve(
        self, plan_id: str, snapshot: PlanSnapshot, ephemeris: EphemerisProvider, progress: Progress
    ) -> SolvedPlan: ...


class Repository(Protocol):
    """Durable catalog, immutable plans, and asynchronous job state."""

    def initialize(self) -> None: ...
    def list_requests(self, offset: int = 0, limit: int = 50, q: str = "") -> dict: ...
    def all_requests(self) -> list[dict]: ...
    def get_request(self, request_id: int) -> dict: ...
    def put_request(self, record: dict, request_id: int | None = None) -> dict: ...
    def add_requests(self, records: list[dict], replace: bool = False) -> int: ...
    def delete_request(self, request_id: int) -> None: ...
    def clear_requests(self) -> int: ...
    def fleet(self) -> list[dict]: ...
    def replace_fleet(self, records: list[dict]) -> None: ...
    def put_spacecraft(self, record: dict) -> None: ...
    def delete_spacecraft(self, spacecraft_id: str) -> None: ...
    def get_setting(self, key: str, default=None): ...
    def set_setting(self, key: str, value) -> None: ...
    def snapshot(self, scenario: dict) -> dict: ...
    def create_job(self, kind: str, request: dict, snapshot: dict, exclusive: bool = True) -> dict: ...
    def get_job(self, job_id: str, include_snapshot: bool = True) -> dict: ...
    def list_jobs(self, limit: int = 30) -> list[dict]: ...
    def update_job(self, job_id: str, **changes) -> None: ...
    def cancel_job(self, job_id: str) -> dict: ...
    def job_cancelled(self, job_id: str) -> bool: ...
    def save_plan(self, solved: SolvedPlan, snapshot: dict) -> None: ...
    def list_plans(self, limit: int = 30) -> list[dict]: ...
    def get_plan(self, plan_id: str) -> dict: ...
    def plan_snapshot(self, plan_id: str) -> dict: ...
    def plan_decisions(
        self,
        plan_id: str,
        status: str | None = None,
        reason: str | None = None,
        offset: int = 0,
        limit: int = 50,
    ) -> dict: ...
    def decision(self, plan_id: str, request_id: int) -> dict: ...
    def plan_instructions(
        self,
        plan_id: str,
        request_id: int | None = None,
        spacecraft_id: str | None = None,
        offset: int = 0,
        limit: int = 100,
    ) -> dict: ...
    def artifact(self, plan_id: str, name: str) -> bytes: ...
    def overview(self) -> dict: ...
